### ISSUE TITLE
Integrate changes in Raiden SCs

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden-monitoring-service#22]
After merge of https://github.com/raiden-network/spec/pull/54 SC calls and messages will require an update.

**Comment by karlb** [comment]
This is solved in https://github.com/raiden-network/raiden-monitoring-service/commit/acecdd3e882f3d8bb22d04704bf0d7c7584c839f and the related changes in raiden-contracts (https://github.com/raiden-network/raiden-contracts/pull/360, https://github.com/raiden-network/raiden-contracts/pull/372).
