### ISSUE TITLE
Split MS into two processes

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-monitoring-service#60]
As suggested in https://github.com/raiden-network/raiden-monitoring-service/issues/37#issuecomment-452704814, splitting the MS into two processes makes DOS attacks on the MS harder. I also expect it to lead to clearer code and better separation of concerns.

The following parts should be moved out of the main MS into a Request Collector:
* all matrix communication
* validation of incoming MRs
* storage of MRs into the database

Then the MS has to only interface with the blockchain and the database.

**Comment by palango** [comment]
This might also make testing easier until we have the matrix broadcasting solution in place.
